security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: admin_login
                check_path: admin_login
                username_parameter: email
                password_parameter: password
                default_target_path: admin_menu
                enable_csrf: true

            logout:
                path: admin_logout
                target: admin_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/register,    roles: PUBLIC_ACCESS }
        - { path: ^/admin,       roles: ROLE_USER }
        - { path: ^/r/,          roles: PUBLIC_ACCESS }
