<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260713021632 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add allergen support: the app-managed Allergen taxonomy (seeded with the 14 EU/UK FIC allergens, extensible via RegulatoryScheme), Global/private ingredient allergen links (the computed source of truth), and per-product allergen overrides (the rare, human-set exception)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, icon VARCHAR(10) NOT NULL, color VARCHAR(20) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_25BF08CE77153098 ON allergen (code)');
        $this->addSql('CREATE TABLE allergen_regulatory_scheme (allergen_id INT NOT NULL, regulatory_scheme_id INT NOT NULL, PRIMARY KEY (allergen_id, regulatory_scheme_id))');
        $this->addSql('CREATE INDEX IDX_CDE0BB776E775A4A ON allergen_regulatory_scheme (allergen_id)');
        $this->addSql('CREATE INDEX IDX_CDE0BB77F0B77011 ON allergen_regulatory_scheme (regulatory_scheme_id)');
        $this->addSql('CREATE TABLE allergen_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(5) NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, allergen_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E190A826E775A4A ON allergen_translation (allergen_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_allergen_locale ON allergen_translation (allergen_id, locale)');
        $this->addSql('CREATE TABLE global_ingredient_allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, presence VARCHAR(20) NOT NULL, global_ingredient_id INT NOT NULL, allergen_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14F88DB5818BC5DD ON global_ingredient_allergen (global_ingredient_id)');
        $this->addSql('CREATE INDEX IDX_14F88DB56E775A4A ON global_ingredient_allergen (allergen_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_global_ingredient_allergen ON global_ingredient_allergen (global_ingredient_id, allergen_id)');
        $this->addSql('CREATE TABLE ingredient_allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, presence VARCHAR(20) NOT NULL, ingredient_id INT NOT NULL, allergen_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57B95840933FE08C ON ingredient_allergen (ingredient_id)');
        $this->addSql('CREATE INDEX IDX_57B958406E775A4A ON ingredient_allergen (allergen_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_ingredient_allergen ON ingredient_allergen (ingredient_id, allergen_id)');
        $this->addSql('CREATE TABLE product_allergen_override (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, presence VARCHAR(20) NOT NULL, note VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, product_id INT NOT NULL, allergen_id INT NOT NULL, set_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AFA19754584665A ON product_allergen_override (product_id)');
        $this->addSql('CREATE INDEX IDX_3AFA19756E775A4A ON product_allergen_override (allergen_id)');
        $this->addSql('CREATE INDEX IDX_3AFA19753E16DC62 ON product_allergen_override (set_by_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_product_allergen_override ON product_allergen_override (product_id, allergen_id)');
        $this->addSql('CREATE TABLE regulatory_scheme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_72D3895977153098 ON regulatory_scheme (code)');
        $this->addSql('ALTER TABLE allergen_regulatory_scheme ADD CONSTRAINT FK_CDE0BB776E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE allergen_regulatory_scheme ADD CONSTRAINT FK_CDE0BB77F0B77011 FOREIGN KEY (regulatory_scheme_id) REFERENCES regulatory_scheme (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE allergen_translation ADD CONSTRAINT FK_5E190A826E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE global_ingredient_allergen ADD CONSTRAINT FK_14F88DB5818BC5DD FOREIGN KEY (global_ingredient_id) REFERENCES global_ingredient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE global_ingredient_allergen ADD CONSTRAINT FK_14F88DB56E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ingredient_allergen ADD CONSTRAINT FK_57B95840933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ingredient_allergen ADD CONSTRAINT FK_57B958406E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_allergen_override ADD CONSTRAINT FK_3AFA19754584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_allergen_override ADD CONSTRAINT FK_3AFA19756E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_allergen_override ADD CONSTRAINT FK_3AFA19753E16DC62 FOREIGN KEY (set_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE allergen_regulatory_scheme DROP CONSTRAINT FK_CDE0BB776E775A4A');
        $this->addSql('ALTER TABLE allergen_regulatory_scheme DROP CONSTRAINT FK_CDE0BB77F0B77011');
        $this->addSql('ALTER TABLE allergen_translation DROP CONSTRAINT FK_5E190A826E775A4A');
        $this->addSql('ALTER TABLE global_ingredient_allergen DROP CONSTRAINT FK_14F88DB5818BC5DD');
        $this->addSql('ALTER TABLE global_ingredient_allergen DROP CONSTRAINT FK_14F88DB56E775A4A');
        $this->addSql('ALTER TABLE ingredient_allergen DROP CONSTRAINT FK_57B95840933FE08C');
        $this->addSql('ALTER TABLE ingredient_allergen DROP CONSTRAINT FK_57B958406E775A4A');
        $this->addSql('ALTER TABLE product_allergen_override DROP CONSTRAINT FK_3AFA19754584665A');
        $this->addSql('ALTER TABLE product_allergen_override DROP CONSTRAINT FK_3AFA19756E775A4A');
        $this->addSql('ALTER TABLE product_allergen_override DROP CONSTRAINT FK_3AFA19753E16DC62');
        $this->addSql('DROP TABLE allergen');
        $this->addSql('DROP TABLE allergen_regulatory_scheme');
        $this->addSql('DROP TABLE allergen_translation');
        $this->addSql('DROP TABLE global_ingredient_allergen');
        $this->addSql('DROP TABLE ingredient_allergen');
        $this->addSql('DROP TABLE product_allergen_override');
        $this->addSql('DROP TABLE regulatory_scheme');
    }
}
