<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds multi-price variants for products (see ProductPriceVariant and
 * Product::$basePriceLabel) and retires the old glass/bottle-only
 * product.glass_price / product.second_price_label columns they replace.
 *
 * Data backfill (defensive only — confirmed 0 rows using glass_price in
 * this dev database, but written in case another environment differs):
 * for every product with glass_price set, product.base_price_label
 * becomes COALESCE(second_price_label, 'Botella') and one
 * product_price_variant row is inserted with label 'Copa', price =
 * glass_price, position 0. "Copa" here is a *recovered convention*, not
 * data that was ever actually stored — the old templates hardcoded it and
 * never persisted it anywhere, so this is the best reconstruction
 * available, not a fact read from a column.
 *
 * down() reverses the schema (drops product_price_variant, recreates the
 * old columns) but does not attempt to reconstruct per-row glass_price /
 * second_price_label values from product_price_variant — same choice
 * Version20260716055404's down() made for ai_suggested: once real usage
 * has happened, there's no way to reliably tell a backfilled "Copa" row
 * apart from one the owner added themselves, so a rollback restores empty
 * columns rather than risking a wrong guess.
 *
 * The auto-generated diff also included unrelated pre-existing schema drift
 * (trigram index drops, DEFAULT-clause mismatches on category/product/
 * product_tag/restaurant columns, a stale unique_tag_locale index) —
 * stripped out here, same as every prior migration this session.
 */
final class Version20260718065436 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add product_price_variant + product.base_price_label; drop product.glass_price / second_price_label';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE product_price_variant (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              label VARCHAR(40) NOT NULL,
              price INT NOT NULL,
              position INT NOT NULL,
              product_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_40886B034584665A ON product_price_variant (product_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE product_price_variant
            ADD CONSTRAINT FK_40886B034584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        $this->addSql('ALTER TABLE product ADD base_price_label VARCHAR(40) DEFAULT NULL');

        // Defensive backfill — see class docblock.
        $this->addSql(<<<'SQL'
            UPDATE product
            SET base_price_label = COALESCE(second_price_label, 'Botella')
            WHERE glass_price IS NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO product_price_variant (label, price, position, product_id)
            SELECT 'Copa', glass_price, 0, id FROM product WHERE glass_price IS NOT NULL
        SQL);

        $this->addSql('ALTER TABLE product DROP glass_price');
        $this->addSql('ALTER TABLE product DROP second_price_label');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_price_variant DROP CONSTRAINT FK_40886B034584665A');
        $this->addSql('DROP TABLE product_price_variant');
        $this->addSql('ALTER TABLE product ADD glass_price INT DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD second_price_label VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE product DROP base_price_label');
    }
}
