<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * AI Menu Import, Phase 1: menu_import_batch / menu_import_page (storage
 * only — no extracted-content columns yet, see MenuImportPage's docblock),
 * plus provenance columns on product/category (importBatch, needsReview,
 * aiConfidence). import_batch_id uses ON DELETE SET NULL, not CASCADE — a
 * confirmed product must never be deleted just because the batch it came
 * from gets discarded later.
 *
 * The auto-generated diff also included unrelated pre-existing schema drift
 * (trigram index naming, DEFAULT-clause mismatches on product_tag/restaurant
 * columns, a stale unique_tag_locale index) and — separately, and actually
 * dangerous — omitted a DEFAULT on `needs_review BOOLEAN NOT NULL`, which
 * would have failed outright against this table's real existing rows
 * (11 products, 5 categories). Both fixed by hand below.
 */
final class Version20260714084551 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'AI menu import Phase 1: menu_import_batch/menu_import_page, and import provenance columns on product/category';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE menu_import_batch (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              status VARCHAR(20) NOT NULL,
              error_message VARCHAR(500) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              restaurant_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6A5C0CBFB1E7706E ON menu_import_batch (restaurant_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE menu_import_page (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              image_path VARCHAR(255) NOT NULL,
              position INT NOT NULL,
              status VARCHAR(20) NOT NULL,
              image_hash VARCHAR(64) NOT NULL,
              error_message VARCHAR(500) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              batch_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_91DA46ECF39EBE7A ON menu_import_page (batch_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE menu_import_batch
            ADD CONSTRAINT FK_6A5C0CBFB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE menu_import_page
            ADD CONSTRAINT FK_91DA46ECF39EBE7A FOREIGN KEY (batch_id) REFERENCES menu_import_batch (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        $this->addSql('ALTER TABLE category ADD needs_review BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE category ADD ai_confidence DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE category ADD import_batch_id INT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE category
            ADD CONSTRAINT FK_64C19C15A310080 FOREIGN KEY (import_batch_id) REFERENCES menu_import_batch (id) ON DELETE SET NULL NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX IDX_64C19C15A310080 ON category (import_batch_id)');

        $this->addSql('ALTER TABLE product ADD needs_review BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE product ADD ai_confidence DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD import_batch_id INT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE product
            ADD CONSTRAINT FK_D34A04AD5A310080 FOREIGN KEY (import_batch_id) REFERENCES menu_import_batch (id) ON DELETE SET NULL NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX IDX_D34A04AD5A310080 ON product (import_batch_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE menu_import_page DROP CONSTRAINT FK_91DA46ECF39EBE7A');
        $this->addSql('ALTER TABLE menu_import_batch DROP CONSTRAINT FK_6A5C0CBFB1E7706E');
        $this->addSql('DROP TABLE menu_import_page');
        $this->addSql('DROP TABLE menu_import_batch');

        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C15A310080');
        $this->addSql('DROP INDEX IDX_64C19C15A310080');
        $this->addSql('ALTER TABLE category DROP needs_review');
        $this->addSql('ALTER TABLE category DROP ai_confidence');
        $this->addSql('ALTER TABLE category DROP import_batch_id');

        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD5A310080');
        $this->addSql('DROP INDEX IDX_D34A04AD5A310080');
        $this->addSql('ALTER TABLE product DROP needs_review');
        $this->addSql('ALTER TABLE product DROP ai_confidence');
        $this->addSql('ALTER TABLE product DROP import_batch_id');
    }
}
