<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds ProductView — one row per de-duplicated customer view of a dish on
 * the public menu (see MenuController::trackView). Hand-trimmed per the same
 * convention as Version20260825011817: the auto-generated diff also picked
 * up unrelated pre-existing schema drift (DROP DEFAULT tweaks, a couple of
 * stale trgm/unique indexes) that isn't part of this change, so only the new
 * table/indexes/constraints are kept here.
 */
final class Version20260826074813 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add product_view table for dish-view analytics';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, restaurant_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7315892FB1E7706E ON product_view (restaurant_id)');
        $this->addSql('CREATE INDEX IDX_7315892F4584665A ON product_view (product_id)');
        $this->addSql('CREATE INDEX idx_product_view_restaurant_created ON product_view (restaurant_id, created_at)');
        $this->addSql('CREATE INDEX idx_product_view_restaurant_product_created ON product_view (restaurant_id, product_id, created_at)');
        $this->addSql('ALTER TABLE product_view ADD CONSTRAINT FK_7315892FB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_view ADD CONSTRAINT FK_7315892F4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_view DROP CONSTRAINT FK_7315892FB1E7706E');
        $this->addSql('ALTER TABLE product_view DROP CONSTRAINT FK_7315892F4584665A');
        $this->addSql('DROP TABLE product_view');
    }
}
