<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260627110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Resync product_tag identity sequence after rows were inserted with explicit IDs';
    }

    public function up(Schema $schema): void
    {
        // The original 8 product_tag rows were inserted with explicit IDs (1–8),
        // so the GENERATED BY DEFAULT AS IDENTITY sequence was never advanced.
        // setval(seq, n) sets last_value = n; the next nextval() returns n+1.
        $this->addSql("SELECT setval('product_tag_id_seq', (SELECT COALESCE(MAX(id), 0) FROM product_tag))");
    }

    public function down(Schema $schema): void
    {
        // Non-reversible — safe to leave as-is; the sequence value is cosmetic.
    }
}
