<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add the Global Ingredient Library (global_ingredient, global_ingredient_translation) and its product association, fully separate from the per-restaurant Ingredient model';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE global_ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(150) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E2A052FB77153098 ON global_ingredient (code)');

        $this->addSql('CREATE TABLE global_ingredient_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(5) NOT NULL, name VARCHAR(255) NOT NULL, global_ingredient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42817AD2818BC5DD ON global_ingredient_translation (global_ingredient_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_global_ingredient_locale ON global_ingredient_translation (global_ingredient_id, locale)');
        $this->addSql('CREATE INDEX idx_global_ingredient_translation_name_trgm ON global_ingredient_translation USING gin (name gin_trgm_ops)');
        $this->addSql('ALTER TABLE global_ingredient_translation ADD CONSTRAINT FK_42817AD2818BC5DD FOREIGN KEY (global_ingredient_id) REFERENCES global_ingredient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE product_global_ingredient (product_id INT NOT NULL, global_ingredient_id INT NOT NULL, PRIMARY KEY (product_id, global_ingredient_id))');
        $this->addSql('CREATE INDEX IDX_562560A84584665A ON product_global_ingredient (product_id)');
        $this->addSql('CREATE INDEX IDX_562560A8818BC5DD ON product_global_ingredient (global_ingredient_id)');
        $this->addSql('ALTER TABLE product_global_ingredient ADD CONSTRAINT FK_562560A84584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_global_ingredient ADD CONSTRAINT FK_562560A8818BC5DD FOREIGN KEY (global_ingredient_id) REFERENCES global_ingredient (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE global_ingredient_translation DROP CONSTRAINT FK_42817AD2818BC5DD');
        $this->addSql('ALTER TABLE product_global_ingredient DROP CONSTRAINT FK_562560A84584665A');
        $this->addSql('ALTER TABLE product_global_ingredient DROP CONSTRAINT FK_562560A8818BC5DD');
        $this->addSql('DROP TABLE product_global_ingredient');
        $this->addSql('DROP TABLE global_ingredient_translation');
        $this->addSql('DROP TABLE global_ingredient');
    }
}
