<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the menu_section table (Primeros/Segundos/Postres group headers
 * inside a fixed-price menu category's dish list). Hand-trimmed: the
 * generated diff also picked up unrelated pre-existing schema drift (stale
 * trigram indexes, DEFAULT-clause mismatches on unrelated columns) — only
 * the new table, its FK, and its index are kept here.
 */
final class Version20260718090148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create menu_section (menu sections interleaved with products by position)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE menu_section (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              label VARCHAR(100) NOT NULL,
              position INT NOT NULL,
              category_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_A5A8675112469DE2 ON menu_section (category_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              menu_section
            ADD
              CONSTRAINT FK_A5A8675112469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE menu_section DROP CONSTRAINT FK_A5A8675112469DE2');
        $this->addSql('DROP TABLE menu_section');
    }
}
