<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds smart_waiter_exchange_log — one row per Smart Waiter chat exchange,
 * aggregated analytics only (provider, model, latency, tokens, estimated
 * cost, success/failure). Never stores message content or conversation
 * text; those live only in the short-TTL cache (SmartWaiterConversationStore).
 *
 * The auto-generated diff also included unrelated pre-existing schema drift
 * (trigram index naming, DEFAULT-clause mismatches on product_tag/restaurant
 * columns, a stale unique_tag_locale index) — stripped out here, same as
 * every prior migration this session; only the new table is this migration's
 * concern.
 */
final class Version20260713083946 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add smart_waiter_exchange_log for Smart Waiter aggregated analytics (no message content)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE smart_waiter_exchange_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              conversation_id VARCHAR(64) NOT NULL,
              locale VARCHAR(10) NOT NULL,
              complexity VARCHAR(10) NOT NULL,
              provider_id VARCHAR(50) DEFAULT NULL,
              model VARCHAR(100) DEFAULT NULL,
              success BOOLEAN NOT NULL,
              failure_reason VARCHAR(20) DEFAULT NULL,
              attempts_count INT NOT NULL,
              latency_ms INT DEFAULT NULL,
              prompt_tokens INT DEFAULT NULL,
              completion_tokens INT DEFAULT NULL,
              estimated_cost_usd DOUBLE PRECISION DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              restaurant_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_99029D0EB1E7706E ON smart_waiter_exchange_log (restaurant_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              smart_waiter_exchange_log
            ADD
              CONSTRAINT FK_99029D0EB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE smart_waiter_exchange_log DROP CONSTRAINT FK_99029D0EB1E7706E');
        $this->addSql('DROP TABLE smart_waiter_exchange_log');
    }
}
