<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608010728 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_tag_assignment (product_id INT NOT NULL, product_tag_id INT NOT NULL, PRIMARY KEY (product_id, product_tag_id))');
        $this->addSql('CREATE INDEX IDX_C6B7B8C74584665A ON product_tag_assignment (product_id)');
        $this->addSql('CREATE INDEX IDX_C6B7B8C7D8AE22B5 ON product_tag_assignment (product_tag_id)');
        $this->addSql('CREATE TABLE product_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, icon VARCHAR(50) NOT NULL, color VARCHAR(20) NOT NULL, position INT NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E3A6E39CB1E7706E ON product_tag (restaurant_id)');
        $this->addSql('CREATE TABLE product_tag_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(5) NOT NULL, name VARCHAR(100) NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9A2B3A12BAD26311 ON product_tag_translation (tag_id)');
        $this->addSql('ALTER TABLE product_tag_assignment ADD CONSTRAINT FK_C6B7B8C74584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_tag_assignment ADD CONSTRAINT FK_C6B7B8C7D8AE22B5 FOREIGN KEY (product_tag_id) REFERENCES product_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product_tag ADD CONSTRAINT FK_E3A6E39CB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_tag_translation ADD CONSTRAINT FK_9A2B3A12BAD26311 FOREIGN KEY (tag_id) REFERENCES product_tag (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product DROP vegetarian');
        $this->addSql('ALTER TABLE product DROP vegan');
        $this->addSql('ALTER TABLE product DROP gluten_free');
        $this->addSql('ALTER TABLE product DROP lactose_free');
        $this->addSql('ALTER TABLE product DROP contains_nuts');
        $this->addSql('ALTER TABLE product DROP halal');
        $this->addSql('ALTER TABLE product DROP kosher');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_tag_assignment DROP CONSTRAINT FK_C6B7B8C74584665A');
        $this->addSql('ALTER TABLE product_tag_assignment DROP CONSTRAINT FK_C6B7B8C7D8AE22B5');
        $this->addSql('ALTER TABLE product_tag DROP CONSTRAINT FK_E3A6E39CB1E7706E');
        $this->addSql('ALTER TABLE product_tag_translation DROP CONSTRAINT FK_9A2B3A12BAD26311');
        $this->addSql('DROP TABLE product_tag_assignment');
        $this->addSql('DROP TABLE product_tag');
        $this->addSql('DROP TABLE product_tag_translation');
        $this->addSql('ALTER TABLE product ADD vegetarian BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE product ADD vegan BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE product ADD gluten_free BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE product ADD lactose_free BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE product ADD contains_nuts BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE product ADD halal BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE product ADD kosher BOOLEAN NOT NULL');
    }
}
