<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Replaces the bare product_ingredient / product_global_ingredient join
 * tables (composite PK only, no ordering) with proper ordered join tables:
 * a surrogate id, an explicit NOT NULL position column, and the old
 * composite key kept as a plain unique constraint instead of the PK.
 *
 * Existing rows are preserved and backfilled with a stable per-product
 * position (ROW_NUMBER() ordered by the old FK id) rather than dropped —
 * this can't recover the *original* printed order for pre-existing data
 * (that was never captured), but it never loses an association, and every
 * row newly created after this migration (via MenuImportAssembler or
 * MenuAdminController::saveProduct()) gets a real, meaningful position.
 *
 * The auto-generated diff also included unrelated pre-existing schema drift
 * (trigram index drops, DEFAULT-clause mismatches on category/product/
 * product_tag/restaurant columns, a stale unique_tag_locale index) —
 * stripped out here, same as every prior migration this session; only the
 * two join tables are this migration's concern.
 */
final class Version20260716045415 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Give product_ingredient / product_global_ingredient an explicit ordered position instead of relying on unordered join-table row order';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_ingredient DROP CONSTRAINT product_ingredient_pkey');
        $this->addSql('ALTER TABLE product_ingredient ADD id INT GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product_ingredient ADD position INT');
        $this->addSql(<<<'SQL'
            UPDATE product_ingredient pi
            SET position = sub.rn - 1
            FROM (
                SELECT product_id, ingredient_id, ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY ingredient_id) AS rn
                FROM product_ingredient
            ) sub
            WHERE pi.product_id = sub.product_id AND pi.ingredient_id = sub.ingredient_id
            SQL);
        $this->addSql('ALTER TABLE product_ingredient ALTER COLUMN position SET NOT NULL');
        $this->addSql('ALTER TABLE product_ingredient ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE product_ingredient ADD CONSTRAINT unique_product_ingredient UNIQUE (product_id, ingredient_id)');

        $this->addSql('ALTER TABLE product_global_ingredient DROP CONSTRAINT product_global_ingredient_pkey');
        $this->addSql('ALTER TABLE product_global_ingredient ADD id INT GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product_global_ingredient ADD position INT');
        $this->addSql(<<<'SQL'
            UPDATE product_global_ingredient pgi
            SET position = sub.rn - 1
            FROM (
                SELECT product_id, global_ingredient_id, ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY global_ingredient_id) AS rn
                FROM product_global_ingredient
            ) sub
            WHERE pgi.product_id = sub.product_id AND pgi.global_ingredient_id = sub.global_ingredient_id
            SQL);
        $this->addSql('ALTER TABLE product_global_ingredient ALTER COLUMN position SET NOT NULL');
        $this->addSql('ALTER TABLE product_global_ingredient ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE product_global_ingredient ADD CONSTRAINT unique_product_global_ingredient UNIQUE (product_id, global_ingredient_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_ingredient DROP CONSTRAINT product_ingredient_pkey');
        $this->addSql('ALTER TABLE product_ingredient DROP CONSTRAINT unique_product_ingredient');
        $this->addSql('ALTER TABLE product_ingredient DROP COLUMN id');
        $this->addSql('ALTER TABLE product_ingredient DROP COLUMN position');
        $this->addSql('ALTER TABLE product_ingredient ADD PRIMARY KEY (product_id, ingredient_id)');

        $this->addSql('ALTER TABLE product_global_ingredient DROP CONSTRAINT product_global_ingredient_pkey');
        $this->addSql('ALTER TABLE product_global_ingredient DROP CONSTRAINT unique_product_global_ingredient');
        $this->addSql('ALTER TABLE product_global_ingredient DROP COLUMN id');
        $this->addSql('ALTER TABLE product_global_ingredient DROP COLUMN position');
        $this->addSql('ALTER TABLE product_global_ingredient ADD PRIMARY KEY (product_id, global_ingredient_id)');
    }
}
