<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260713063700 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add classification_log: a generic, reusable audit trail + review queue for AI-assisted data enrichment (see App\Service\Classification), starting with Global Ingredient allergen classification';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE classification_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject_type VARCHAR(50) NOT NULL, subject_id INT NOT NULL, classification_type VARCHAR(50) NOT NULL, label VARCHAR(100) DEFAULT NULL, attributes JSON DEFAULT NULL, confidence DOUBLE PRECISION DEFAULT NULL, status VARCHAR(20) NOT NULL, source VARCHAR(10) NOT NULL, review_note VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_classification_lookup ON classification_log (subject_type, subject_id, classification_type)');
        $this->addSql('CREATE UNIQUE INDEX unique_classification_subject_label ON classification_log (subject_type, subject_id, classification_type, label)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE classification_log');
    }
}
