parameters:
    exchange_api_key: '%env(EXCHANGE_API_KEY)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\ExchangeRateUpdater:
        arguments:
            $exchangeApiKey: '%exchange_api_key%'
